version: "3.8"

services:
  postgres:
    image: 'postgres:17'
    restart: always
    container_name: todo-list-db
    environment:
      - POSTGRES_DB=dspappas-todo-list
      - POSTGRES_USER=Dspappas1
      - POSTGRES_PASSWORD=Dspappas123!@#
    ports:
      - 5434:5432


  postgres-testing:
    image: 'postgres:latest'
    restart: always
    container_name: todo-list-test-db
    environment:
      - POSTGRES_DB=dspappas-todo-list-testing
      - POSTGRES_USER=Dspappas1Test
      - POSTGRES_PASSWORD=Dspappas123!@#Test
    ports:
      - 5435:5432