spring:
  main:
    banner-mode: "off"  # Disables Spring Boot banner on startup

  datasource:
    url: jdbc:postgresql://localhost:5434/dspappas-todo-list
    username: Dspappas1
    password: Dspappas123!@#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Prevents accidental schema changes
    show-sql: false  # Set to 'true' for debugging queries

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true  # Enforces proper naming conventions